# Generated by Django 4.1.7 on 2023-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='news_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
